In [2]:
import pandas as pd
import seaborn as sns
import matplotlib as plt
import numpy as np

# Join data

In [3]:
df = pd.read_csv('C:\\Users\\Buster\\Documents\\MSc\\Project\\Flask_App_WPB\\wpb-flask\\Modelling\\countries.csv', encoding='latin-1')

In [4]:
df.head()

,WPBname,name,id,geo_id,region_id,colour,region,CIAname,population,gdp,gdp_rank,life_expectancy,edu_expenditure_pct_gdp,literacy,unemployment,health_expenditure_pct_gdp,pct_poverty_line
0,Andorra,Andorra,1,AD,6,DC143C,Europe,Andorra,85708.0,49900.0,32.0,82.9,3.2,100.0,3.7,8.1,NaN
1,United Arab Emirates,United Arab Emirates,2,AE,1,FFAEB9,Asia,United Arab Emirates,9701315.0,68600.0,13.0,78.7,NaN,93.8,1.6,3.6,19.5
2,Afghanistan,Afghanistan,3,AF,1,CD8C95,Asia,Afghanistan,34940837.0,2000.0,209.0,52.1,3.9,38.2,23.9,8.2,54.5
3,Antigua and Barbuda,Antigua and Barbuda,4,AG,8,8B5F65,Northern America,Antigua And Barbuda,95882.0,26400.0,78.0,76.9,2.5,99.0,11.0,5.5,NaN
4,Anguilla (United Kingdom),Anguilla,5,AI,8,FFC0CB,Northern America,Anguilla,17422.0,12200.0,130.0,81.6,NaN,NaN,8.0,NaN,23.0

In [9]:
df['countryref_id'] = df['id']

In [10]:
df.shape

(222, 18)

In [7]:

df_data = pd.read_csv(r'C:\Users\Buster\Documents\MSc\Project\Flask_App_WPB\wpb-flask\Modelling\\country_datas.csv', encoding='latin-1')

df_data.tail()

,id,countryref_id,country,metric_id,metric,year,value,exp_value
4669,4792,222,Zimbabwe,2,Prison population Rate,2008,103.0,NaN
4670,4793,222,Zimbabwe,2,Prison population Rate,2010,96.0,NaN
4671,4794,222,Zimbabwe,2,Prison population Rate,2012,115.0,NaN
4672,4795,222,Zimbabwe,2,Prison population Rate,2014,115.0,NaN
4673,4796,222,Zimbabwe,2,Prison population Rate,2017,120.0,NaN

In [6]:
df_data.shape

(4674, 8)

In [12]:
all_metrics = df_data.merge(df, on = 'countryref_id', how = 'left')

In [13]:
all_metrics.describe()

,id_x,countryref_id,metric_id,year,value,exp_value,id_y,region_id,population,gdp,gdp_rank,life_expectancy,edu_expenditure_pct_gdp,literacy,unemployment,health_expenditure_pct_gdp,pct_poverty_line
count,4674.000000,4674.000000,4674.000000,4674.000000,4.595000e+03,0.0,4674.000000,4674.000000,4.578000e+03,4572.000000,4572.000000,4548.000000,3662.000000,3446.000000,4418.000000,4070.000000,3658.000000
mean,2387.230210,111.020539,2.069961,2011.119384,2.020455e+04,NaN,111.020539,4.356012,3.669800e+07,24413.998250,110.238408,73.653298,4.674167,85.726175,10.291761,6.877494,26.510607
std,1382.335963,63.729739,1.351076,6.712770,1.313151e+05,NaN,63.729739,2.896591,1.412585e+08,24993.223952,63.928255,7.431084,1.811404,17.686442,10.088790,2.715407,17.129077
min,1.000000,1.000000,1.000000,1993.000000,0.000000e+00,NaN,1.000000,1.000000,9.038000e+03,700.000000,1.000000,52.100000,0.800000,19.100000,0.300000,1.500000,0.200000
25%,1191.250000,57.000000,1.000000,2006.000000,7.300000e+01,NaN,57.000000,2.000000,7.406850e+05,6300.000000,55.000000,68.900000,3.500000,78.400000,4.200000,5.000000,14.900000
50%,2378.500000,112.000000,2.000000,2012.000000,1.940000e+02,NaN,112.000000,3.000000,6.312212e+06,15200.000000,109.000000,75.400000,4.500000,94.400000,7.000000,6.500000,22.400000
75%,3588.750000,164.000000,2.000000,2019.000000,3.725000e+03,NaN,164.000000,6.000000,2.564096e+07,36400.000000,163.000000,78.900000,5.500000,98.500000,12.200000,8.600000,35.000000
max,4796.000000,222.000000,6.000000,2019.000000,2.307504e+06,NaN,222.000000,9.000000,1.384689e+09,139100.000000,228.000000,89.400000,12.800000,100.000000,77.000000,17.100000,82.500000

In [14]:
all_metrics.shape

(4674, 25)

In [16]:
all_metrics

,id_x,countryref_id,country,metric_id,metric,year,value,exp_value,WPBname,name,...,CIAname,population,gdp,gdp_rank,life_expectancy,edu_expenditure_pct_gdp,literacy,unemployment,health_expenditure_pct_gdp,pct_poverty_line
0,1,160,Papua New Guinea,1,Prison Population Total,2019,5087.0,NaN,Papua New Guinea,Papua New Guinea,...,Papua New Guinea,7027332.0,3700.0,184.0,67.5,NaN,64.2,2.5,4.3,37.0
1,2,181,Slovakia,1,Prison Population Total,2019,10372.0,NaN,Slovakia,Slovakia,...,Slovakia,5445040.0,33100.0,61.0,77.4,4.6,NaN,8.1,8.1,12.3
2,3,104,Kyrgyzstan,1,Prison Population Total,2019,10574.0,NaN,Kyrgyzstan,Kyrgyzstan,...,Kyrgyzstan,5849296.0,3700.0,183.0,71.2,7.2,99.5,7.1,6.5,32.1
3,4,113,Kazakhstan,1,Prison Population Total,2019,31001.0,NaN,Kazakhstan,Kazakhstan,...,Kazakhstan,18744548.0,26300.0,79.0,71.4,2.9,99.8,5.0,4.4,2.6
4,5,43,Colombia,1,Prison Population Total,2019,119896.0,NaN,Colombia,Colombia,...,Colombia,48168996.0,14400.0,116.0,76.2,4.4,94.7,9.3,7.2,28.0
5,6,125,Morocco,1,Prison Population Total,2019,82512.0,NaN,Morocco,Morocco,...,Morocco,34314130.0,8600.0,147.0,77.3,5.3,68.5,10.2,5.9,15.0
6,7,68,United Kingdom: England & Wales,1,Prison Population Total,2019,82543.0,NaN,United Kingdom: England & Wales,United Kingdom,...,United Kingdom,65105246.0,44300.0,39.0,80.9,5.5,NaN,4.4,9.1,15.0
7,8,172,Russian Federation,1,Prison Population Total,2019,557584.0,NaN,Russian Federation,Russian Federation,...,Russia,142122776.0,27900.0,74.0,71.3,3.8,99.7,5.2,7.1,13.3
8,9,163,Poland,1,Prison Population Total,2019,73520.0,NaN,Poland,Poland,...,Poland,38420687.0,29600.0,69.0,77.9,4.8,99.8,4.9,6.4,17.6
9,10,90,Indonesia,1,Prison Population Total,2019,258501.0,NaN,Indonesia,Indonesia,...,Indonesia,262787403.0,12400.0,127.0,73.2,3.6,95.4,5.4,2.8,10.9
10,11,159,French Polynesia (France),1,Prison Population Total,2019,573.0,NaN,French Polynesia (France),French Polynesia,...,French Polynesia,290373.0,17000.0,103.0,77.5,NaN,NaN,21.8,NaN,19.7
11,12,66,France,1,Prison Population Total,2019,70059.0,NaN,France,France,...,France,67364357.0,44100.0,40.0,82.0,5.5,NaN,9.4,11.5,14.2
12,13,71,French Guiana/Guyane (France),1,Prison Population Total,2019,784.0,NaN,French Guiana/Guyane (France),French Guiana,...,Guyana,740685.0,8100.0,151.0,68.9,6.3,88.5,11.1,5.2,35.0
13,14,220,South Africa,1,Prison Population Total,2019,164129.0,NaN,South Africa,South Africa,...,South Africa,55380210.0,13600.0,118.0,64.1,6.1,94.4,27.5,8.8,16.6
14,15,140,Mauritius,1,Prison Population Total,2019,2626.0,NaN,Mauritius,Mauritius,...,Mauritius,1364283.0,22300.0,86.0,76.0,5.0,93.2,7.1,4.8,8.0
15,16,133,Myanmar (formerly Burma),1,Prison Population Total,2019,92000.0,NaN,Myanmar (formerly Burma),Myanmar,...,Burma,55622506.0,6300.0,163.0,68.6,0.8,75.6,4.0,2.3,25.6
16,17,158,Peru,1,Prison Population Total,2019,90638.0,NaN,Peru,Peru,...,Peru,31331228.0,13500.0,119.0,74.2,3.9,94.2,6.9,5.5,22.7
17,18,102,Japan,1,Prison Population Total,2019,51805.0,NaN,Japan,Japan,...,Japan,126168156.0,42900.0,42.0,85.5,3.5,NaN,2.9,10.2,16.1
18,19,175,Solomon Islands,1,Prison Population Total,2019,477.0,NaN,Solomon Islands,Solomon Islands,...,Solomon Islands,660121.0,2200.0,207.0,75.8,9.9,84.1,NaN,5.1,NaN
19,20,180,Slovenia,1,Prison Population Total,2019,1333.0,NaN,Slovenia,Slovenia,...,Slovenia,2102126.0,34500.0,58.0,81.2,4.9,99.7,6.6,9.2,13.9
20,21,151,Netherlands,1,Prison Population Total,2019,10464.0,NaN,Netherlands,Netherlands,...,Netherlands,17151228.0,53900.0,23.0,81.5,5.4,NaN,4.9,10.9,8.8
21,22,52,Denmark,1,Prison Population Total,2019,3635.0,NaN,Denmark,Denmark,...,Denmark,5809502.0,50100.0,30.0,81.0,7.6,NaN,5.7,10.8,13.4
22,23,161,Philippines,1,Prison Population Total,2019,188278.0,NaN,Philippines,Philippines,...,Philippines,105893381.0,8400.0,148.0,69.6,2.7,96.3,5.7,4.7,21.6
23,24,153,Nepal,1,Prison Population Total,2019,18881.0,NaN,Nepal,Nepal,...,Nepal,29717587.0,2700.0,195.0,71.3,5.1,63.9,3.0,5.8,25.2
24,25,134,Mongolia,1,Prison Population Total,2019,3099.0,NaN,Mongolia,Mongolia,...,Mongolia,3103428.0,13000.0,120.0,70.2,4.1,98.4,8.0,4.7,29.6
25,26,211,St. Vincent and the Grenadines,1,Prison Population Total,2019,469.0,NaN,St. Vincent and the Grenadines,Saint Vincent and the Grenadines,...,Saint Vincent And The Grenadines,101844.0,11500.0,133.0,75.8,5.8,NaN,18.8,8.6,NaN
26,27,116,St. Lucia,1,Prison Population Total,2019,527.0,NaN,St. Lucia,Saint Lucia,...,Saint Lucia,165510.0,14400.0,117.0,78.1,5.7,NaN,20.0,6.7,NaN
27,28,5,Anguilla (United Kingdom),1,Prison Population Total,2019,55.0,NaN,Anguilla (United Kingdom),Anguilla,...,Anguilla,17422.0,12200.0,130.0,81.6,NaN,NaN,8.0,NaN,23.0
28,29,182,Sierra Leone,1,Prison Population Total,2019,4519.0,NaN,Sierra Leone,Sierra Leone,...,Sierra Leone,6312212.0,1600.0,219.0,59.0,4.6,48.1,15.0,11.1,70.2
29,30,55,Algeria,1,Prison Population Total,2019,60000.0,NaN,Algeria,Algeria,...,Algeria,41657488.0,15200.0,109.0,77.2,NaN,80.2,11.7,7.2,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4644,4767,214,Virgin Islands (USA),2,Prison population Rate,2000,475.0,NaN,Virgin Islands (USA),"Virgin Islands, U.S.",...,Virgin Islands,106977.0,37000.0,54.0,79.5,NaN,NaN,10.4,NaN,28.9
4645,4768,214,Virgin Islands (USA),2,Prison population Rate,2002,599.0,NaN,Virgin Islands (USA),"Virgin Islands, U.S.",...,Virgin Islands,106977.0,37000.0,54.0,79.5,NaN,NaN,10.4,NaN,28.9
4646,4769,214,Virgin Islands (USA),2,Prison population Rate,2004,533.0,NaN,Virgin Islands (USA),"Virgin Islands, U.S.",...,Virgin Islands,106977.0,37000.0,54.0,79.5,NaN,NaN,10.4,NaN,28.9
4647,4770,214,Virgin Islands (USA),2,Prison population Rate,2006,548.0,NaN,Virgin Islands (USA),"Virgin Islands, U.S.",...,Virgin Islands,106977.0,37000.0,54.0,79.5,NaN,NaN,10.4,NaN,28.9
4648,4771,214,Virgin Islands (USA),2,Prison population Rate,2008,572.0,NaN,Virgin Islands (USA),"Virgin Islands, U.S.",...,Virgin Islands,106977.0,37000.0,54.0,79.5,NaN,NaN,10.4,NaN,28.9
4649,4772,214,Virgin Islands (USA),2,Prison population Rate,2010,544.0,NaN,Virgin Islands (USA),"Virgin Islands, U.S.",...,Virgin Islands,106977.0,37000.0,54.0,79.5,NaN,NaN,10.4,NaN,28.9
4650,4773,214,Virgin Islands (USA),2,Prison population Rate,2012,542.0,NaN,Virgin Islands (USA),"Virgin Islands, U.S.",...,Virgin Islands,106977.0,37000.0,54.0,79.5,NaN,NaN,10.4,NaN,28.9
4651,4774,218,Yemen,2,Prison population Rate,1998,84.0,NaN,Yemen,Yemen,...,Yemen,28667230.0,2500.0,199.0,66.2,NaN,70.1,27.0,5.6,54.0
4652,4775,218,Yemen,2,Prison population Rate,2003,84.0,NaN,Yemen,Yemen,...,Yemen,28667230.0,2500.0,199.0,66.2,NaN,70.1,27.0,5.6,54.0
4653,4776,218,Yemen,2,Prison population Rate,2006,49.0,NaN,Yemen,Yemen,...,Yemen,28667230.0,2500.0,199.0,66.2,NaN,70.1,27.0,5.6,54.0
4654,4777,218,Yemen,2,Prison population Rate,2009,48.0,NaN,Yemen,Yemen,...,Yemen,28667230.0,2500.0,199.0,66.2,NaN,70.1,27.0,5.6,54.0
4655,4778,218,Yemen,2,Prison population Rate,2011,42.0,NaN,Yemen,Yemen,...,Yemen,28667230.0,2500.0,199.0,66.2,NaN,70.1,27.0,5.6,54.0
4656,4779,221,Zambia,2,Prison population Rate,1998,146.0,NaN,Zambia,Zambia,...,Zambia,16445079.0,4000.0,178.0,53.0,NaN,63.4,15.0,5.0,54.4
4657,4780,221,Zambia,2,Prison population Rate,2000,116.0,NaN,Zambia,Zambia,...,Zambia,16445079.0,4000.0,178.0,53.0,NaN,63.4,15.0,5.0,54.4
4658,4781,221,Zambia,2,Prison population Rate,2002,123.0,NaN,Zambia,Zambia,...,Zambia,16445079.0,4000.0,178.0,53.0,NaN,63.4,15.0,5.0,54.4
4659,4782,221,Zambia,2,Prison population Rate,2005,124.0,NaN,Zambia,Zambia,...,Zambia,16445079.0,4000.0,178.0,53.0,NaN,63.4,15.0,5.0,54.4
4660,4783,221,Zambia,2,Prison population Rate,2008,120.0,NaN,Zambia,Zambia,...,Zambia,16445079.0,4000.0,178.0,53.0,NaN,63.4,15.0,5.0,54.4
4661,4784,221,Zambia,2,Prison population Rate,2010,128.0,NaN,Zambia,Zambia,...,Zambia,16445079.0,4000.0,178.0,53.0,NaN,63.4,15.0,5.0,54.4
4662,4785,221,Zambia,2,Prison population Rate,2012,116.0,NaN,Zambia,Zambia,...,Zambia,16445079.0,4000.0,178.0,53.0,NaN,63.4,15.0,5.0,54.4
4663,4786,221,Zambia,2,Prison population Rate,2014,109.0,NaN,Zambia,Zambia,...,Zambia,16445079.0,4000.0,178.0,53.0,NaN,63.4,15.0,5.0,54.4
4664,4787,221,Zambia,2,Prison population Rate,2016,114.0,NaN,Zambia,Zambia,...,Zambia,16445079.0,4000.0,178.0,53.0,NaN,63.4,15.0,5.0,54.4
4665,4788,222,Zimbabwe,2,Prison population Rate,2000,164.0,NaN,Zimbabwe,Zimbabwe,...,Zimbabwe,14030368.0,2300.0,203.0,61.1,7.5,86.5,11.3,6.4,72.3
4666,4789,222,Zimbabwe,2,Prison population Rate,2002,165.0,NaN,Zimbabwe,Zimbabwe,...,Zimbabwe,14030368.0,2300.0,203.0,61.1,7.5,86.5,11.3,6.4,72.3
4667,4790,222,Zimbabwe,2,Prison population Rate,2004,152.0,NaN,Zimbabwe,Zimbabwe,...,Zimbabwe,14030368.0,2300.0,203.0,61.1,7.5,86.5,11.3,6.4,72.3
4668,4791,222,Zimbabwe,2,Prison population Rate,2006,137.0,NaN,Zimbabwe,Zimbabwe,...,Zimbabwe,14030368.0,2300.0,203.0,61.1,7.5,86.5,11.3,6.4,72.3
4669,4792,222,Zimbabwe,2,Prison population Rate,2008,103.0,NaN,Zimbabwe,Zimbabwe,...,Zimbabwe,14030368.0,2300.0,203.0,61.1,7.5,86.5,11.3,6.4,72.3
4670,4793,222,Zimbabwe,2,Prison population Rate,2010,96.0,NaN,Zimbabwe,Zimbabwe,...,Zimbabwe,14030368.0,2300.0,203.0,61.1,7.5,86.5,11.3,6.4,72.3
4671,4794,222,Zimbabwe,2,Prison population Rate,2012,115.0,NaN,Zimbabwe,Zimbabwe,...,Zimbabwe,14030368.0,2300.0,203.0,61.1,7.5,86.5,11.3,6.4,72.3
4672,4795,222,Zimbabwe,2,Prison population Rate,2014,115.0,NaN,Zimbabwe,Zimbabwe,...,Zimbabwe,14030368.0,2300.0,203.0,61.1,7.5,86.5,11.3,6.4,72.3
4673,4796,222,Zimbabwe,2,Prison population Rate,2017,120.0,NaN,Zimbabwe,Zimbabwe,...,Zimbabwe,14030368.0,2300.0,203.0,61.1,7.5,86.5,11.3,6.4,72.3

In [17]:
all_metrics.isna().sum()

id_x                             0
countryref_id                    0
country                          0
metric_id                        0
metric                           0
year                             0
value                           79
exp_value                     4674
WPBname                          0
name                             0
id_y                             0
geo_id                          20
region_id                        0
colour                           0
region                           0
CIAname                         96
population                      96
gdp                            102
gdp_rank                       102
life_expectancy                126
edu_expenditure_pct_gdp       1012
literacy                      1228
unemployment                   256
health_expenditure_pct_gdp     604
pct_poverty_line              1016
dtype: int64

# Descriptive Statistics

In [38]:
#separate dfs for each of the metrics

ppt = all_metrics[all_metrics.metric_id ==1]
ppt = ppt[ppt.value.notna()]

ppr = all_metrics[all_metrics.metric_id ==2]
ppr = ppr[ppr.value.notna()]

remand = all_metrics[all_metrics.metric_id ==3]
remand = remand[remand.value.notna()]

fem = all_metrics[all_metrics.metric_id ==4]
fem = fem[fem.value.notna()]

foreign = all_metrics[all_metrics.metric_id ==5]
foreign = foreign[foreign.value.notna()]

occ = all_metrics[all_metrics.metric_id ==6]
occ = occ[occ.value.notna()]

In [39]:
occ.shape

(201, 25)

In [ ]:
#g = sns.pairplot(ppt)

In [55]:
columns = ['value', 'population', 'gdp', 'gdp_rank',
       'life_expectancy', 'edu_expenditure_pct_gdp', 'literacy',
       'unemployment', 'health_expenditure_pct_gdp', 'pct_poverty_line']

In [ ]:
correlation = ppt.corr(method='pearson')


correlation_map = np.corrcoef(ppt[columns])
sns.set(font_scale=1.0)
heatmap = sns.heatmap(correlation_map, cbar=True, annot=True, square=True, fmt='.2f', yticklabels=columns, xticklabels=columns)

plt.show()